# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command

[build]
  publish = "build"
  command = "node getPasswords.js && npm run build"
