# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: netlify-cms # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.json"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
      - file: "content/settings/global-yaml.yml"
        label: "Global Settings - Yaml"
        name: "global-settings-yaml"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/home.json"
        label: "Home Page"
        name: "home-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Body, name: body, widget: markdown}
      # markdown files are ok
      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Section 1, name: section1, widget: markdown}
          - {label: Section 2, name: section2, widget: markdown}
      - file: "content/pages/contact.json"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Body, name: body, widget: markdown}
