# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: store
    label: Store
    editor:
      preview: true
    create: false
    delete: false
    files:
      - file: content/store/store.json
        label: Products
        name: products
        fields:
          - label: Product
            name: products
            widget: list
            fields:
              - {label: Name, name: title, widget: string}
              - {label: Price, name: price, widget: number, required: true}
              - {label: BriefDescription, name: briefDescription, widget: markdown}
              - {label: Primary Image, name: primaryImage, widget: image, required: true}
              - {label: FullDescription, name: longDescription, widget: markdown}
              - label: "Images"
                name: "images"
                widget: "list"
                required: true
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
              - label: "Options"
                name: "options"
                widget: "list"
                required: false
                fields:
                  - label: "0ption Title"
                    name: "option"
                    widget: string
                  - label: Extra Cost
                    name: cost
                    widget: number
                  - label: Calculate Stock for This Option Separately
                    name: separateStock
                    widget: boolean
                  - label: Stock for This Option (if selected above)
                    name: stock
                    widget: number
              - label: Current Stock
                name: 'stock'
                widget: number
              - label: Shipping Class
                name: class
                widget: relation
                collection: shippingClasses
                searchFields: ["title"]
                valueField: "title"
              - label:  M Shipping Class
                name: Mclass
                widget: mrelation
                collection: shippingClasses
                searchFields: ["title"]
                valueField: "title"
              - label: 'Status'
                name: 'status'
                widget: 'select'
                options: ["Published", "Featured", "Draft"]
                default: 'Published'
              - {label: Date / Order, name: date, widget: date}
              - label: "Meta"
                required: false
                name: "meta"
                widget: "object"
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
                  - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
                  - {label: Noindex, name: noindex, widget: boolean, required: false}
  - name: products
    label: Product
    editor:
      preview: true
    folder: content/products
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Test Widget"
        name: "test"
        widget: "stock"
      - label: "Plain Test Widget"
        name: "plaintest"
        widget: "test"
      - label: "RelationSelect"
        name: "relationSelect"
        widget: "relationSelect"
      - {label: Name, name: title, widget: "string"}
      - {label: Price, name: price, widget: number, required: true}
      - {label: BriefDescription, name: briefDescription, widget: markdown}
      - {label: Primary Image, name: primaryImage, widget: image, required: true}
      - {label: FullDescription, name: longDescription, widget: markdown}
      - label: "Images"
        name: "images"
        widget: "list"
        required: true
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
      - label: "Options"
        name: "options"
        widget: "list"
        required: false
        fields:
          - label: "0ption Title"
            name: "option"
            widget: string
          - label: Extra Cost
            name: cost
            widget: number
          - label: Calculate Stock for This Option Separately
            name: separateStock
            widget: boolean
          - label: Stock for This Option (if selected above)
            name: stock
            widget: number
      - label: Current Stock
        name: 'stock'
        widget: number
      - label: Shipping Class
        name: class
        widget: relation
        collection: shippingClasses
        searchFields: ["title"]
        valueField: "title"
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ["Published", "Featured", "Draft"]
        default: 'Published'
      - {label: Date / Order, name: date, widget: date}
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
          - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
          - {label: Noindex, name: noindex, widget: boolean, required: false}

  - name: shippingClasses
    label: Shipping Class
    editor:
      preview: false
    folder: content/shipping
    create: true
    fields:
      - {label: Name, name: title, widget: string}
      - label: Carriers
        name: carriers  
        widget: list
        fields:
          - label: Carrier
            name: carrier
            widget: string
          - label: Regions
            name: regions
            widget: list
            fields:
              - label: Region Title
                name: region
                widget: string
              - label: Cost
                name: cost
                widget: number
              - label: Max Ship Together as One
                name: maxPack
                widget: number
          
  - name: "pages"
    label: Contact, About, Blog, Home
    create: false
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Show, name: show, widget: boolean, default: true}
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - {label: Body, name: body, widget: markdown}
          - {label: Address, name: address, widget: text}
          - {label: Phone, name: phone, widget: string}
          - {label: Email Address, name: email, widget: string}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/blog.md"
        label: "Blog Page"
        name: "blog-page"
        fields:
          - {label: Show, name: show, widget: boolean, default: true}
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Show, name: show, widget: boolean, default: false}
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - {label: Section 1, name: section1, widget: markdown}
          - {label: Section 2, name: section2, widget: markdown}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {label: Show, name: show, widget: boolean, , default: false}
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Subtitle, name: subtitle, widget: markdown}
          - {label: Body, name: body, widget: markdown}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string, required: false}
              - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
              - {label: Noindex, name: noindex, widget: boolean, required: false}

  - name: posts
    label: Blog Post
    editor:
      preview: true
    folder: content/posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ["Published", "Featured", "Draft"]
        default: 'Published'
      - {label: Date / Order, name: date, widget: date}
      - {label: Post Featured Image, name: postFeaturedImage, widget: image, required: false}
      - {label: Excerpt, name: excerpt, widget: text}
      - {label: Content, name: body, widget: markdown}
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
        fields:
          - label: "Category"
            name: "category"
            widget: "relation"
            collection: "postCategories"
            searchFields: ["title"]
            valueField: "title"
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
          - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
          - {label: Noindex, name: noindex, widget: boolean, required: false}

  - name: postCategories
    label: Blog Post Category
    editor:
      preview: false
    folder: content/postCategories
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
          - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
          - {label: Noindex, name: noindex, widget: boolean, required: false}


  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
          - {label: Enable Service Worker Pre-Cache, name: enableServiceWorker, widget: boolean, required: false}

  - name: "inventory"
    label: "Inventory"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/stock.json"
        label: "Set/View Inventory"
        name: "stock"
        fields:
          - label: "Product Stock"
            name: "productStock"
            widget: "list"
            required: false
            fields:
              - label: "Product Type"
                name: "productType"
                widget: "relation"
                collection: "products"
                searchFields: ["title"]
                valueField: "title"
              - {label: SetStock, name: currentStock, widget: number, required: true}

  - name: "inventoryTEST"
    label: "InventoryTEST"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/settings/stockTEST.json"
        label: "Set/View Inventory"
        name: "stockTEST"
        fields:
          - label: "Product Stock"
            name: "productStock"
            widget: "list"
            required: false
            fields: # The fields each document in this collection have
              - {label: Name, name: title, widget: string}
              - label: 'Status'
                name: 'status'
                widget: 'select'
                options: ["Published", "Featured", "Draft"]
                default: 'Published'
              - {label: Date / Order, name: date, widget: date}
              - {label: Price, name: price, widget: number, required: true}
              - {label: Primary Image, name: primaryImage, widget: image, required: true}
              - {label: BriefDescription, name: briefDescription, widget: markdown}
              - {label: FullDescription, name: longDescription, widget: markdown}
              - label: "Images"
                name: "images"
                widget: "list"
                required: true
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
              - label: "Options"
                name: "options"
                widget: "list"
                required: false
                fields:
                  - label: "option"
                    name: "option"
                    widget: string
              - label: "Meta"
                required: false
                name: "meta"
                widget: "object"
                fields:
                  - {label: Title, name: title, widget: string, required: false}
                  - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
                  - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
                  - {label: Noindex, name: noindex, widget: boolean, required: false}
